### ISSUE TITLE
Get request is returning an empty array

### ISSUE THREAD

**Issue by atakori** [atakori/Mongoose-blog-api#1]
I am guessing this has to do with the request not really accessing the database but I am not sure why

**Comment by krokhale** [comment]
Just looked at your server.js file, you don't have the index route defined. That's why you don't see anything when you type in localhost:8080 in your browser.

Copying a line from your previous server. This is what you might want:

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/views/index.html');
});

Let me know if that solves the issue, or if i have misunderstood what you said.

**Comment by atakori** [comment]
[SOLVED] mongoose creates looks for collections names in all lowercase. We previously named our collection using camel case which was causing it to look for a collection that was not there
